#!/usr/bin/env bash
set -eux

# Only on control
if [[ "$(hostname)" != "control" ]]; then
  exit 0
fi

# Update and install Ansible
sudo apt-get update
sudo apt-get install -y software-properties-common
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt-get install -y ansible

# Configure SSH to not ask "Are you sure?"
cat <<EOF >> ~/.ssh/config
Host 192.168.56.*
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null
EOF

# Create basic inventory
mkdir -p ~/ansible
cat <<EOF > ~/ansible/hosts.ini
[web]
web01 ansible_host=192.168.56.11 ansible_user=ec2-user
web02 ansible_host=192.168.56.12 ansible_user=ec2-user

[db]
db01  ansible_host=192.168.56.13 ansible_user=ec2-user

[all:vars]
ansible_ssh_private_key_file=/vagrant/control_key.pem
EOF

# Copy the key generated by Vagrant
cp /vagrant/.vagrant/machines/control/virtualbox/private_key ~/ansible/control_key.pem
chmod 600 ~/ansible/control_key.pem

echo "===>> Control node ready! Inventory is located at ~/ansible/hosts.ini"
