---
- name: Provisioning Server 
  hosts: all
  become: yes
  tasks:
    - name: Install chrony on Centos 
      yum:
        name: "{{item}}"
        state: present
        update_cache: yes
      when: ansible_distribution == "CentOS"
      loop:
        - chrony
        - wget
        - git
        - zip
        - unzip

    - name: Install ntp on Ubuntu
      apt:
         name: "{{item}}"
         state: present
         update_cache: yes
      when: ansible_distribution == "Ubuntu"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Start & enable chron on Redhat
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Start & enable chron on Debian
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Add group
      group:
         name: devops
         state: present

    - name: Add users
      user:
          name: "{{item}}"
          state: present
          groups: devops
      loop: "{{usernames}}"
